# A Dockerfile for development/testing

version: "3.5"

services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    ports:
      - "4006:80"
    # env_file:
    #   - config/dev/public.env
    #   - config/dev/secrets.env
    environment:
      - DATABASE_HOST=db
    # depends_on:
    #   - db
    #   - search
    volumes:
      - type: bind
        source: ../
        target: /forks
        read_only: true
      - type: bind
        source: .
        target: /opt/app
    stdin_open: true # like docker run -i
    tty: true # like docker run -t
  # db:
  #   image: postgis/postgis:12-3.0-alpine
  #   volumes:
  #     - "./data/postgres/dev:/var/lib/postgresql/data"
  #   # ports:
  #   #   - "5432:5432"
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #   # env_file:
  #   #   - config/dev/public.env
  #   #   - config/dev/secrets.envs
